title = "Welcome Bug Engineer!"
body = """
The company is requesting the production of 100,000 Bug Guts to supply the next off-world ship with food. 
The current assembly line is way too slow to get it done within this millennia, it's only a single hive and grinder!
See to it's improvement, feel free to use Bug Guts along the way to bolster it's capacity and mutate the bugs into something juicier!

== Instructions ==
Hives produce infinite basic bugs, use mutation screens to change their properties into juicer bugs (Bugs that produce more Guts).
Tenderizing the Bug before it reaches the grinder produces more Guts as well, this includes the number of bounces off of surfaces as well as how hard they bounce off the surface.
"""