name: Build Game

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  ITCH_USERNAME: realliance
  ITCH_GAME_ID: ssj-2023

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev libxcb-xfixes0-dev libxcb-shape0-dev cmake mingw-w64 zip
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install Just
      run: cargo install just wasm-bindgen-cli
    - name: Build Game
      run: just client-wasm-opt
    - name: Publish to Itch.io
      uses: KikimoraGames/itch-publish@v0.0.3
      with:
        butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
        gameData: web
        itchUsername: ${{ env.ITCH_USERNAME }}
        itchGameId: ${{ env.ITCH_GAME_ID }}
        buildChannel: webgl
